# Generated by Django 6.0.2 on 2026-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
    ]
